### ISSUE TITLE
greaterThan.modifier.test dates as string wrong timezone

### ISSUE THREAD

**Issue by atiertant** [balderdashy/waterline-adapter-tests#104]
using new Date() to insert and a static string to search could not work in every timezone...
you should replace it by a date object toString() like in [offshore-adapter-test PR-2](https://github.com/Atlantis-Software/offshore-adapter-tests/pull/2)

**Comment by atiertant** [comment]
why adapters should receive strings instead of date and handle it...
it would be better to do it in waterline before sending it to adapter...(writting an adapter would be easier)
what do you think of this?

**Comment by particlebanana** [comment]
@atiertant currently we don't do any casting on criteria objects which is why this test is there. I'll update it to work better with timezones.
