### ISSUE TITLE
rename `associations` interface for clarity

### ISSUE THREAD

**Issue by mikermcneil** [balderdashy/waterline-adapter-tests#11]
@particlebanana are you ok with renaming the `associations` interface to `relational` to capture the idea that it's only relevant if your data source supports SQL/relational joins (or a simulation of such)?  All this stuff w/ Redis lately has me confused when I look at it, and I bet that might happen to other folks too.  Also down if you (or anyone else reading this who's read the interface spec) has other ideas

**Comment by tjwebb** [comment]
I think we're beyond the point of no return with this one :)
