### ISSUE TITLE
why groupBy with no calculations has to raise an error ?

### ISSUE THREAD

**Issue by postsql** [balderdashy/waterline-adapter-tests#13]
queries/modifiers/groupBy.query.modifier.test.js  has this test :

it('should error if not given any calculations to do', function(done) {
      User.find({
        groupBy: ['type']
      }, function(err, summed) {
        assert(err);
        done();
      });
    });

Why is this defined to raise an error
IMO this is simple DISTINCT query and not an error.

SELECT "type" FROM "user" GROUP BY "type";

or

SELECT DISTINCT "type" FROM "user";

**Comment by dmarcelino** [comment]
Any updates on this?

**Comment by devinivy** [comment]
I think this is primarily a waterline-sequel thing: https://github.com/balderdashy/waterline-sequel/blob/4c084466d2af3ab5c64d98327fd4b65c7581200e/sequel/select.js#L127-L130

I don't believe it's enforced in waterline core.

**Comment by dmarcelino** [comment]
Good catch @devinivy, I think we can close this for now then.

**Comment by devinivy** [comment]
I've moved this over to https://github.com/balderdashy/waterline-sequel/issues/47 for now.  @dmarcelino we should think about how the tests should deal with adapters that do/do not support groupBy and especially aggregates.  And on the waterline core end, will that functionality have to go into the integrator?  Any pertinent issues should be split-off from this one.  Thanks for bringing this up @postsql !
