### ISSUE TITLE
Two-way 1:1 associations tests

### ISSUE THREAD

**Issue by robmoggach** [balderdashy/waterline-adapter-tests#15]
I don't see any tests for two way 1:1 associations...

btw... these tests are great docs for Sails associations while we wait for the docs!

## Use case:
* **User** model and **Person** model
* **User** has a **profile** attribute which is a **Person**
* **Person** has an optional **user** attribute which is a **User**

**Comment by dmarcelino** [comment]
Hi @robmoggach, there are tests for the 1:m association tests which are essentially two-way 1:1 associations. Can we close this?

**Comment by dmarcelino** [comment]
Closing this as unresponsive please reopen if you want to resume this issue/discussion. Thanks
