### ISSUE TITLE
Can we change the tableName for tests to lowercase only?

### ISSUE THREAD

**Issue by Powpow-Shen** [balderdashy/waterline-adapter-tests#21]
Hi there,
The reason I am asking is because I am writing an adapter for couchdb, and there is no collection in couchdb (not like mongo). So in order to write an adapter for couchdb, I have to create databases to use for table/collection. But currently, the rule for creating databases of couchdb is "Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed.
 Must begin with a letter.". So I have difficulty to run integration tests, becuase the tableName is in carmelcase, ex: userTable, userTable1, ...
So my question is can we change the tableName to lowercase only?

**Comment by dmarcelino** [comment]
@Powpow-Shen, is this still an issue? https://github.com/tjwebb/sails-couchdb-orm/commit/39a34386ed5f00c8a43d0e70241370768d1b2bb4 looks like a good solution for this.

**Comment by dmarcelino** [comment]
Closing this as unresponsive, please reopen if you want to resume the issue/discussion. Thanks
