### ISSUE TITLE
Broken tests involving 'sorting by id'

### ISSUE THREAD

**Issue by adityamukho** [balderdashy/waterline-adapter-tests#22]
Some tests have started sorting the results by id, and then testing properties of the retrieved elements against the inserted elements with the assumption that the returned result set would have maintained the insert order. (Since fb8863a97647782d6334cff9908f6f03e3efbd97 - `not.modifier.test.js`, `lessThan.modifier.test.js`).

However, sorting by id need not return elements as per the insert order, for adapters that use a string-based primary key.

My [adapter](https://github.com/adityamukho/sails-nedb) for the NeDB datastore uses string-based ids and hence fails on the tests where such a sorting step is present.

If sorting is required, maybe we can achieve more consistent behaviour across datastores by sorting on a separate numeric attribute that we manually assign?

**Comment by dmarcelino** [comment]
@adityamukho can you submit a PR addressing the broken tests? Also look at https://github.com/balderdashy/waterline-adapter-tests/issues/26#issuecomment-95901573. Thanks.

**Comment by devinivy** [comment]
@dmarcelino is this addressed now with those recent PRs?

**Comment by dmarcelino** [comment]
@devinivy, my recent PRs did not address `not.modifier.test.js` nor all cases where `lessThan.modifier.test.js` was using `sort: 'id asc'`. PR #59 fixes this issue.
