### ISSUE TITLE
ID order faillure

### ISSUE THREAD

**Issue by atiertant** [balderdashy/waterline-adapter-tests#26]
in test like [waterline-adapter-tests/interfaces/queryable/modifiers/not.modifier.test.js](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/queryable/modifiers/not.modifier.test.js)

insertions:
        for(var i=40; i<44; i++) {
          users.push({ first_name: testName, age: i, email: i + '@test.com' });
        }

        Queryable.User.createEach(users, function(err) {
          if(err) return done(err);
          done();
        });

test:
      it('should return records with string usage', function(done) {
        Queryable.User.find({ first_name: testName, age: { not: 40 }})
        .sort('id asc')
        .exec(function(err, users) {
          assert(!err);
          assert(Array.isArray(users));
          assert(users.length === 3);
          assert(users[0].age === 41);

if databases insert all data whith autoincrement value in the strict order they are requested,all is ok.
but what about if one record take more or less time to be inserted that the other because of network,asynchronous call or anything else...

my question is : does adapter MUST unsure insert and autoincrement value are in the same order as createEach array data? or shoud the test sort by other column?

**Comment by dmarcelino** [comment]
Good question @atiertant, I believe it's the latter. If you look at #52 and #43 some changes have been made in that direction.

@atiertant, is this breaking the tests for an adapter you are developing?

@devinivy, what are your thoughts on this?

**Comment by atiertant** [comment]
@dmarcelino, yes in sails-oracledb, we need to add sort by primary key if no sort were used because oracle have no default order.

**Comment by dmarcelino** [comment]
@atiertant in the specific case you mentioned it's possible to sort by age. Can you submit a PR? Thanks

**Comment by devinivy** [comment]
As far as I know, `createEach` should insert records in order per https://github.com/balderdashy/waterline/commit/be228a2f20f9c00c17948cbdc323d2340ea49853

**Comment by atiertant** [comment]
@devinivy, if it's a waterline spec so this should work now,i'll test but doesn't it break performance?

**Comment by dmarcelino** [comment]
Indeed @atiertant, there is some discussion about it in https://github.com/balderdashy/sails-postgresql/issues/128#issuecomment-95907716.

**Comment by devinivy** [comment]
@atiertant I believe adapters are also encouraged to implement their own `createEach` method if performance is a concern.

**Comment by dmarcelino** [comment]
I doubt most adapters implement `createEach`... and I think we should replace that `async.eachSeries` with `async.map` to maximize performance. If the order of creating is critical for someone they can still chain a few `create()` operations in a `async.eachSeries`.

**Comment by dmarcelino** [comment]
@devinivy, slightly off topic (but not completely), can you give a quick look at PR #27, I think it's good to be merged.

**Comment by atiertant** [comment]
@dmarcelino , using async.map would product the same problem in tests because as insert could be done in any order by database,sorting them by id in find does not unsure having them in same order.

@devinivy , the real question is should waterline createEach return insert in the order of their real insertion (map) or createEach shoud insert in the strict order they were passed and return so (eachSeries) ? first is faster and not sure second as any interest ...

**Comment by dmarcelino** [comment]
@atiertant, I've proposed #980 to replace `async.eachSeries` for `async.map` and I believe the tests should be independent of the `id`. For example, by default [RethinkDB](http://rethinkdb.com/api/javascript/table_create/) uses as uuid for id which it's natural order is pretty much worthless.

**Comment by atiertant** [comment]
@dmarcelino so waterline find function shoud not sort by id by default too.this change many things in an oracle adapter.thanks for your answer.we will PR tests independent of the id.

**Comment by atiertant** [comment]
@dmarcelino:  https://github.com/balderdashy/waterline-adapter-tests/pull/60

**Comment by dmarcelino** [comment]
Closed via #60, thanks @atiertant.
