### ISSUE TITLE
make use of assert.equal and other descriptive methods

### ISSUE THREAD

**Issue by tjwebb** [balderdashy/waterline-adapter-tests#30]
Specifically, `assert.equal` should always be used with strings. Some string comparisons will fail triple-equality check. I've run into this in getting the tests to pass in the couch adapter.

From a UX perspective, the methods will produce more helpful and descriptive failure messages.

**Comment by dmarcelino** [comment]
:+1:

**Comment by devinivy** [comment]
Yes, yes!  A lot of the newer tests have this.
For those who had to look-up what comparison problem @tjwebb is referencing,
>```
"abc" == new String("abc")    // true
"abc" === new String("abc")   // false
```
(http://stackoverflow.com/questions/359494/does-it-matter-which-equals-operator-vs-i-use-in-javascript-comparisons)

**Comment by dmarcelino** [comment]
PR  #69 should take care of this.

**Comment by dmarcelino** [comment]
PR #70 replaces #69.
