### ISSUE TITLE
Allow individual tests to be skipped

### ISSUE THREAD

**Issue by searls** [balderdashy/waterline-adapter-tests#33]
So we're making great progress on our adapter and we have two remaining failing tests, but because of how Parse.com works, we actually _expect_ those failures. Meanwhile, we want to have a green CI build, so we're left to wonder how to disable or skip just those two tests.

1. Is there already a mechanism in the suite or with mocha to skip specifically identified tests without editing the source of the test
2. If not, should there be?

In the meantime, we may choose to fork this repo and punch out the tests we know don't apply to us (in our case the find SQL injection  and find auto-increment).

**Comment by dmarcelino** [comment]
Hi @searls, I think the best solution for this is #35 after it gets merged.

**Comment by dmarcelino** [comment]
@searls, given #35 has been merged you will be able to skip specific tests by adding the following to your runner.js file inside options:

``` javascript
    // Mocha options
    // reference: https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically
    mocha: {
      grep: /unsupported feature 1 test|unsupported feature 2 test/
    },

    mochaChainableMethods: {
      // inverts the above grep
      invert: true,
    }
```

Please reopen if this doesn't fix your issue.
