### ISSUE TITLE
Official adapter findOrCreateEach failures

### ISSUE THREAD

**Issue by devinivy** [balderdashy/waterline-adapter-tests#38]
With the adapter tests now testing against official adapters, we find that several adapters are failing findOrCreateEach tests.  It seems related to changes in waterline after 0.10.18.  Perhaps right around here: https://github.com/balderdashy/waterline/commit/7226da33aebf30c3e8469daf269872929d288e33 ?  This issue can be used for discussion.  If we pinpoint the issue, we can close this and open relevant issues on waterline core and/or any adapters.

**Comment by dmarcelino** [comment]
@Globegitter submitted PR balderdashy/waterline#845. @Globegitter, any ideas how we can fix these [tests](https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/55985131)? Thanks

**Comment by devinivy** [comment]
I wonder if it may have to do with this non-incrementing `i`
https://github.com/balderdashy/waterline/commit/7226da33aebf30c3e8469daf269872929d288e33#diff-207f71a79a3988d38c925642f0c6fa2cR93

**Comment by Globegitter** [comment]
That might be it - I will take a look over the next as soon as I can over the next few days.

**Comment by dmarcelino** [comment]
@devinivy, I think you are right. In the current tests `attributesToCheck ===  [ 'type', 'first_name' ]`, so not an array of collections as the in code implies.

I've replaced the highlighted block for:
```javascript
      attributesToCheck.forEach(function (attrName) {
        criteria[attrName] = values[attrName];
      });
```

And it passes all the test I can run manually (not postgresql/mysql).

**Comment by dmarcelino** [comment]
Take a look at https://github.com/balderdashy/waterline/tree/findOrCreateEach_fix: 3ed1a20

**Comment by dmarcelino** [comment]
Alright, so I've set up a branch with the integration tests pointing at this findOrCreateEach branch with the fix and the results are positive, no findOrCreateEach tests broken. sails-postresql and sails-mysql pass all tests. You can check it here:
https://travis-ci.org/dmarcelino/waterline-adapter-tests/jobs/56162491#L496

And you can compare it with integration tests that ran against waterline master branch:
https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/56141632

I'll issue a PR.

**Comment by dmarcelino** [comment]
PR balderdashy/waterline#905 issued.

**Comment by Globegitter** [comment]
@dmarcelino thank you for fixing that!

**Comment by dmarcelino** [comment]
No problem, @Globegitter :smiley:

**Comment by Globegitter** [comment]
@dmarcelino Now I remember again why I changed the code. I am on the latest waterline `0.10.20`, so the fix with
```js
attributesToCheck.forEach(function (attrName) {
  criteria[attrName] = values[attrName];
});
```
is in place again and it breaks my app.

The parameters `criteria` and `values` are both arrays of objects, so the `forEach` loop returns the whole object as `attrName`.

Don't quite understand why `attributesToCheck` is just an array of values in the tests as you posted.

**Comment by dmarcelino** [comment]
@Globegitter, I wonder if the tests themselves have an issue or are testing a different scenario than yours?

**Comment by Globegitter** [comment]
@dmarcelino I am investigating now. But I was sure the tests I wrote covered that scenario. Investigating now and will update.

**Comment by Globegitter** [comment]
@dmarcelino That is pretty strange. This test https://github.com/balderdashy/waterline/blob/master/test/unit/query/query.findOrCreate.js#L61 covers the scenario and if you place some console.logs you can indeed see that `criteria { '[object Object]': undefined }`, but also `values` already seem to have been created, since it is:
```js
{ name: 'Foo Bar',
  createdAt: Mon Apr 06 2015 14:44:44 GMT+0100 (BST),
  updatedAt: Mon Apr 06 2015 14:44:44 GMT+0100 (BST) }
```

And that is why the tests pass. But no idea why `values` has already been created at this point.

Here is the line in the code I am talking about btw: https://github.com/balderdashy/waterline/blob/master/lib/waterline/adapter/aggregateQueries.js#L92

**Comment by dmarcelino** [comment]
@Globegitter, running the [waterline-adapter-tests - findOrCreateEach.test.js](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/semantic/findOrCreateEach.test.js) with sails-memory I see:

 `attributesToCheck === [ 'type', 'first_name' ]`
 `criteria === {}`
``` javascript
  values === { type: 'findOrCreateEach([])',
  first_name: 'NOT IN THE SET',
  favoriteFruit: 'blueberry',
  status: false,
  createdAt: Mon Apr 06 2015 14:54:24 GMT+0100 (WEST),
  updatedAt: Mon Apr 06 2015 14:54:24 GMT+0100 (WEST) }
```

**Comment by Globegitter** [comment]
Changing the code to what I actually had intended at the beginning works in my apps and tests carry on working strangely enough:
```js
var i = 0;

    async.eachSeries(valuesList, function (values, cb) {
      if (!_.isObject(values)) return cb(new Error('findOrCreateEach: Unexpected value in valuesList.'));
      // Check that each of the criteria keys match:
      // build a criteria query
      var criteria = {};

      Object.keys(attributesToCheck[i]).forEach(function (attrName, i) {
        criteria[attrName] = values[attrName];
      });

      i++;

      return self.findOrCreate.call(self, criteria, values, function (err, model) {
        if(err) return cb(err);

        // Add model to list
        if(model) models.push(model);

        cb(null, model);
      });
    }, function (err) {
      if(err) return cb(err);
      cb(null, models);
    });
```

**Comment by dmarcelino** [comment]
@Globegitter, have you tried running the sails-memory integration tests with your changes?

**Comment by Globegitter** [comment]
Ahhh now I see what the issue is. You are looking at the tests of `findOrCreateEach`. Seems that this usage is undocumented. Also the `findOrCreateEach` itself is deprecated not documented.

**Comment by dmarcelino** [comment]
Yeah, that's what started this thread: broken integration tests. :)

If `findOrCreateEach` is deprecated we should remove it on `0.11`. In the meantime it would be good to have a solution that satisfies both your app and (all) the tests.

**Comment by Globegitter** [comment]
Yeah I am not sure what exactly the intentions are. From what I can see it still is being used internally, so maybe it is just deprecated as public API.

But yeah you are right, it should still satisfy current tests. Just installing everything on my local machine and testing against it and will submit a PR that satisfies my app and all the current tests :)

**Comment by Globegitter** [comment]
On a side note, it still is strange that https://github.com/balderdashy/waterline/blob/master/test/unit/query/query.findOrCreate.js#L61 passes, even though it creates bogus for the criteria. But not sure how that situation could be improved.

**Comment by dmarcelino** [comment]
Meanwhile I found PR #843, which does in fact suggest `findOrCreateEach` is to be deprecated in 0.11.

Good stuff, thanks.

**Comment by devinivy** [comment]
It appears that the tests are used quite differently than how @Globegitter uses `findOrCreateEach`.  The first argument should be an array of attributes to `findOne` on for each object in the second argument.  The function signature hints at this: 
```
function(attributesToCheck, valuesList, cb)
```

**Comment by dmarcelino** [comment]
PS: raised balderdashy/waterline#931 to discuss the future of `findOrCreateEach`.

**Comment by Globegitter** [comment]
Interesting. Now that makes a bit more sense. I think one of the problems that makes the code quite hard to read is that there are multiple `findOrCreateEach`. In https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/composite.js for example you have `findOrCreate: function(criteria, values, cb)` which on the other hand suggests a similar usage to the `find` or `update`.
