### ISSUE TITLE
tests semantic types doesn't test stored value

### ISSUE THREAD

**Issue by atiertant** [balderdashy/waterline-adapter-tests#65]
as you can see in waterline-adapter-tests/interfaces/semantic/types/binary.type.js and others
value is checked with the result of create.
this shoud work in a perfect world but not in some adapters: to optimize create function,the result of create is the input object with addtion of the database returned id. (no need to make a find that would take more time in the adapter).
in this case the test will ever pass without testing data stored in database.
a better solution would be to add a find in test to unsure value has been stored and could be read correctly.

**Comment by dmarcelino** [comment]
Hi @atiertant, that sounds reasonable. Can you submit a pull request? Thanks

**Comment by atiertant** [comment]
@dmarcelino done https://github.com/balderdashy/waterline-adapter-tests/pull/66

**Comment by dmarcelino** [comment]
Fixed via #66. Thanks @atiertant.
