### ISSUE TITLE
can't install waterline-adapter-tests dependencies

### ISSUE THREAD

**Issue by sushilkumar48** [balderdashy/waterline-adapter-tests#82]
I am unable to install waterline-adapter-tests dependencies which are linked to github in package.json. I couldn't figure out where is the issue. But the npm error log says unable to access the git repo (all those which are linked to github in package.json).

Here are the error logs:
npm WARN package.json waterline-trydb@0.10.0 No repository field.
npm ERR! git clone --template=/home/cretif/.npm/_git-remotes/_templates --mirror https://github.com/balderdashy/sails-memory.git /home/cretif/.npm/_git-remotes/https-github-com-balderdashy-sails-memory-git-df73bacf: Cloning into bare repository '/home/cretif/.npm/_git-remotes/https-github-com-balderdashy-sails-memory-git-df73bacf'...
npm ERR! git clone --template=/home/cretif/.npm/_git-remotes/_templates --mirror https://github.com/balderdashy/sails-memory.git /home/cretif/.npm/_git-remotes/https-github-com-balderdashy-sails-memory-git-df73bacf: fatal: unable to access 'https://github.com/balderdashy/sails-memory.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received
npm ERR! Linux 3.13.0-54-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "waterline-adapter-tests" "--save-dev"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/cretif/.npm/_git-remotes/_templates --mirror https://github.com/balderdashy/sails-memory.git /home/cretif/.npm/_git-remotes/https-github-com-balderdashy-sails-memory-git-df73bacf
npm ERR! Cloning into bare repository '/home/cretif/.npm/_git-remotes/https-github-com-balderdashy-sails-memory-git-df73bacf'...
npm ERR! fatal: unable to access 'https://github.com/balderdashy/sails-memory.git/': Operation timed out after 0 milliseconds with 0 out of 0 bytes received

Also are you guys developing any adapter for inlfuxdb (or any other time-series database)?

Thanks

**Comment by dmarcelino** [comment]
That looks very weird... but it looks like that there were issues connecting to github to clone the repo which caused your issue. Have you tried again since then?

> Also are you guys developing any adapter for inlfuxdb (or any other time-series database)?

No.

**Comment by sushilkumar48** [comment]
I explored the issue on github and found that it is a bug in npm. Whenever packages(in package.json) are linked to github repo using ssh/http, npm's regex parsing can't fetch the correct path and gives an error. Later I downloaded this repo and added the same in node_modules manually and then installed all dependencies and it worked. Now I can run the tests.

Request: I couldn't found a good documentation/guide/tutorial to build a custom-adapter. I am beginner level developer and got interested in sails the moment I read about it. I want to link few models to influxdb and there is no adapter available for that. The boilerplate code is helpful but not enough to get things done very fast. It would be nice if you provide and example of custom-adapter development or sails' docs.

Thanks.

**Comment by dmarcelino** [comment]
Currently your best starting points are: https://github.com/balderdashy/waterline-docs/blob/master/adapters/adapters.md and https://github.com/balderdashy/sails-generate-adapter

After that I recommend taking a look at existing adapters code such as https://github.com/balderdashy/sails-mongo.

As you proceed feel free to submit PRs against the waterline-docs, this area of the docs can certainly be improved!
