### ISSUE TITLE
Refactor tests that expect autoPK to be true

### ISSUE THREAD

**Issue by jmdobry** [balderdashy/waterline-adapter-tests#9]
See [waterline #157](https://github.com/balderdashy/waterline/issues/157).

RethinkDB does not support `autoPK`, and therefore cannot pass the tests that expect `autoPK` to be true, namely:

[definitions.test#L46](https://github.com/balderdashy/waterline-adapter-tests/blob/master/lib/collection/definitions.test.js#L46)

and

[create.test#L81](https://github.com/balderdashy/waterline-adapter-tests/blob/master/lib/collection/create.test.js#L81)

**Comment by dmarcelino** [comment]
@jmdobry, is this still an issue?

**Comment by jmdobry** [comment]
> @jmdobry, is this still an issue?

@dmarcelino Not for me, as I moved on from Waterline a long time ago, but RethinkDB still does not support auto-incrementing primary keys, so I imagine this is still an issue for that reason.

**Comment by dmarcelino** [comment]
Thanks @jmdobry.
